---
title: The Butler
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: "/"
canonicalurl: true
keywords:
- Cecil
- Static Site Generator
- SSG
author: Arnaud Ligny
date: 2020-12-06 23:00:00 +0000
theme:
- hyde
- netlify
- netlify-cms
hyde:
  sidebar:
    sticky: true
  theme: ''
  reverse: true
draft: true
